spring:
  devtools:
    add-properties: false
  mvc:
    view: 
      prefix: WEB-INF/static/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
      url: jdbc:mysql://192.168.2.19:3306/RAJA_DB
      username: "0050"
      password: "Aalam%153"
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true   
       